### ISSUE TITLE
Is there any support for database encryption?

### ISSUE THREAD

**Issue by RallyTronics** [Remi-Coulom/joedb#4]
How would you handle this?

**Comment by Remi-Coulom** [comment]
There is support for opening a database from a C++ i/o stream. So if you have a C++ stream that does encryption/decryption, then you can use joedb with it.

I searched and found this:
https://github.com/benhj/CryptoStreamPP

Using joedb with a C++ stream might not be well documented at the moment. If you are interested, I will document it more. I have been thinking about releasing a new version soon, so this might be the opportunity to do it.

**Comment by RallyTronics** [comment]
I would greatly appreciate it if you can document the stream interface.  

Thanks!

**Comment by Remi-Coulom** [comment]
OK. I will prepare a new release. I expect to do this at the beginning of next week.

**Comment by Remi-Coulom** [comment]
Hi,

joedb should be now ready for its next release. I will do some more testing and polishing, and will make the official release in a few days.

For the moment, you can get the latest code from the git repository. I uploaded the new documentation, with some example code of how to open a joedb database from a C++ stream:
https://www.remi-coulom.fr/joedb/opening_files.html

You may also like to take a look at the release notes:
https://www.remi-coulom.fr/joedb/history.html

I hope you can make database encryption work with this new version.

**Comment by RallyTronics** [comment]
Thanks for your help, this is a very useful library.
