### ISSUE TITLE
feature request: support arrays in the schema

### ISSUE THREAD

**Issue by RallyTronics** [Remi-Coulom/joedb#6]
In my .joedbi file i have some table definitions like this where I need a row of 64 doubles:

create_table data_64
add_field data_64 c0 float64
add_field data_64 c1 float64
add_field  data_64 c2 float64
...
add_field data_64 c62 float64
add_field data_64 c62 float64
add_field data_64 c63 float64

It would be much easier to access the data if I could do something like:
create_table data_64
add_field data_64 c float64[64]

such that data_of_data_64 looks something like this:
struct data_of_data_64
{
 std::array<double, 64> field_value_of_c;
}

Is there a different way to get the same result?

**Comment by RallyTronics** [comment]
Maybe I can use std::span as a workaround

**Comment by Remi-Coulom** [comment]
I would do it this way:

```
create_table double
add_field double value float64

create_table data_of_data_64
add_field data_of_data_64 field_value references double
```

Then in C++, you could manipulate objects like this:

```
auto x = db.new_data_of_data_64(db.new_vector_of_double(64));
db.set_value(db.get_field_value(x)[12], 123.0f);
```

This data structure does not enforce at the schema level that the vectors are of size 64. But, if you want to, you should be able to wrap database accesses with your own C++ functions that enforce the constraint.

**Comment by RallyTronics** [comment]
Cool, thanks!

**Comment by Remi-Coulom** [comment]
In case you had not noticed, there is some documentation there:
https://www.remi-coulom.fr/joedb/vectors.html
