### ISSUE TITLE
Is this a variant of prevayler?

### ISSUE THREAD

**Issue by sptrakesh** [Remi-Coulom/joedb#7]
Hello,

Saw a link on cppcast, and on browsing initial documentation this seems very similar to prevayler.  I had done quite a bit of work with prevayler a long time ago (10+ years), and was just curious if that was where the original idea came from.

Looks cool, will see if a use case comes up for this.

**Comment by Remi-Coulom** [comment]
Hi,

Thanks for letting me know about prevayler. I had never heard of it. There are indeed many similarities with joedb. I added a link to prevayler to the documentation, where you can find a collection of links to other related software and ideas: https://www.remi-coulom.fr/joedb/links.html
